### ISSUE TITLE
mvn virgo:start problem

### ISSUE THREAD

**Issue by mcheung63** [frieder/virgo-maven-plugin#2]
/root/workspace/PLib>mvn virgo:start
[INFO] Scanning for projects...
[WARNING] The POM for net.flybyte.virgo:virgo-maven-plugin:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for net.flybyte.virgo:virgo-maven-plugin:1.0.0: Plugin net.flybyte.virgo:virgo-maven-plugin:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.flybyte.virgo:virgo-maven-plugin:jar:1.0.0
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (11 KB at 271.2 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (22 KB at 538.5 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.752s
[INFO] Finished at: Fri Feb 15 09:51:08 HKT 2013
[INFO] Final Memory: 9M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'virgo' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), central (http://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
/root/workspace/PLib>

**Comment by nfalco79** [comment]
Your project could found the virgo plugins simple because these plugins are not plublished in none distribution system so you have to build them (clean install as describe in README) on the machine you are running the above code.
